version: '3.3'
services:
  filebup:
    image: ghcr.io/lucasmchoi/filebup:latest
    container_name: filebup
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ~/Docker/config:/filebup/config
      - ~/Pathtobackup/:/filebup/volumes